//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetENTITY_Framework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PMSDbEntities : DbContext
    {
        public PMSDbEntities()
            : base("name=PMSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<FetchProducts_Result> FetchProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchProducts_Result>("FetchProducts");
        }

        internal void GetPRoductNameByID(int prdId, ObjectParameter objpara)
        {
            throw new NotImplementedException();
        }
    }
}
